config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tasks#index'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'accounts' => 'user_accounts#index'
  get 'account/:id/edit' => 'user_accounts#edit'
  post 'account/:id/edit' => 'user_accounts#update'
  delete 'account/:id/destroy' => 'user_accounts#destroy'

  get 'tasks/new' => 'tasks#new'
  post 'tasks/new' => 'tasks#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  attachment :image_id
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :name, presence: true
    validates :account_id, presence: true, uniqueness: true

    has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
        user = User.find_by(account_id: params[:session][:account_id])
        if user&.authenticate(params[:session][:password])
            login user
            redirect_to root_path
        else
            flash.now[:alert] = 'アカウントID、またはパスワードが間違っています'
            render :new
        end
    end

    def destroy
        logout
        redirect_to login_path
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :login_required

    def index
        
    end

    def new
      @task = Task.new
    end

    def create

    end

    private

    def login_required
        redirect_to login_path unless logged_in?
    end
    
end

app/controllers/user_accounts_controller.rb
class UserAccountsController < ApplicationController
  def index
    @users_info = User.all
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:notice] = "削除されました"
    redirect_to accounts_path
  end

  def edit
    @info = User.find(params[:id])
  end

  def update
    @info = User.find(params[:id])
    @info.name = params[:name]
    @info.account_id = params[:account_id]
    if @info.save
      flash[:notice] = "ユーザー情報の変更を完了しました"
      redirect_to accounts_path
    else
      render("/account/#{@info.id}/edit")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        render :new unless @user.save
    end

    private

    def user_params
        params.require(:user).permit(:name, :account_id, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def login(user)
        session[:user_id] = user.id
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        current_user.present?
    end

    def logout
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_accounts_helper.rb
module UserAccountsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>SISWeb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ujs/1.2.2/rails.js"></script>
</head>

<body>
    <%= yield %>
</body>

</html>

app/views/tasks/index.html.erb
<p>Welcome <%= current_user.name %>!</p>

<%= link_to 'ユーザ一覧', accounts_path %>
<%= link_to 'ログアウト', logout_path, method: :delete %>

<%= link_to '新規投稿', tasks_new_path %>

app/views/tasks/new.html.erb
<%= form_with url: "/tasks/new", local: true do |f| %>
<%= flash[:alert] %>
<p>
    <%= f.label :name, 'タイトル' %>
    <%= f.text_field :name %>
</p>

<p>
    <%= f.label :image, '投稿画像' %>
    <%= f.attachment_field :image %>
</p>

<p><%= f.submit '投稿' %></p>
<% end %>

app/views/user_accounts/edit.html.erb
<%# form_withを使用したかったが、謎のエラーにより断念%>

<% @info.errors.full_messages.each do |message| %>
<%= message %>
<% end %>

<%= form_tag("/account/#{@info.id}/edit") %>
<p>ユーザー名</p>
<input name="name" value="<%= @info.name %>">
<p>アカウントID</p>
<input name="account_id" value="<%= @info.account_id %>">
<input type="submit" value="変更">

app/views/user_accounts/index.html.erb
<ul>
    <% @users_info.each do |info| %>
    <li>
        <%= info.name %>
        <%= info.account_id %>
        <%= link_to '編集', "account/#{info.id}/edit" %> <%#名前付きルートを断念　今後改善%>
        <% if current_user.id != info.id %>
        <%= link_to '削除', "account/#{info.id}/destroy", method: :delete %>
        <% end %>
    </li>
    <% end %>
</ul>

<%= link_to  "投稿一覧", root_path %>

app/views/user_accounts/show.html.erb
<h1>UserAccounts#show</h1>
<p>Find me in app/views/user_accounts/show.html.erb</p>

app/views/users/create.html.erb
<p>登録完了しました!</p>
<p><%= link_to 'ログインページ', login_path %>からログインしてご利用ください</p>

app/views/users/new.html.erb
<%= form_with model: @user, url: signup_path, local: true do |f| %>
<% if @user.errors.any? %>
<ul>
    <%= @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
</ul>
<% end %>

<p>
    <%= f.label :name, 'お名前' %>
    <%= f.text_field :name, required: true %>
</p>

<p>
    <%= f.label :account_id, 'アカウントID' %>
    <%= f.text_field :account_id, required: true %>
</p>

<p>
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, required: true %>
</p>

<p>
    <%= f.label :password_confirmation, 'パスワード(確認)' %>
    <%= f.password_field :password_confirmation, required: true %>
</p>

<p><%= f.submit '送信' %></p>
<% end %>